# Generated by Django 5.0 on 2024-01-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_options'),
        ('tasks', '0004_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='tasks',
            field=models.ManyToManyField(related_name='labels', to='tasks.task'),
        ),
    ]
