# Generated by Django 5.0 on 2024-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_remove_label_tasks'),
        ('tasks', '0004_alter_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='labels.label'),
        ),
    ]
