# Generated by Django 5.0 on 2024-01-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
    ]
